spring.application.name=RentCote

# ── Supabase PostgreSQL (Session Pooler) ──
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.houzzwvwsaubglihbbzm&password=RentCote_2000
spring.datasource.username=postgres.houzzwvwsaubglihbbzm
spring.datasource.password=RentCote_2000
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ── CORS (permitir frontend en localhost:3000) ──
server.port=8080
